{% set version = "0.1.43" %}
{% set name = "jaxlib" %}

{% set pyver = "cp{}{}".format(PY_VER[0], PY_VER[2]) %}

{% set platform = "manylinux2010_x86_64" %}  # [linux]
{% set platform = "macosx_10_9_x86_64" %}  # [osx]

# {distribution}-{version}(-{build tag})?-{python tag}-{abi tag}-{platform tag}.whl.
{% set fn = "{}-{}-{}-none-{}.whl".format(name, version, pyver, platform) %}

package:
  name: jaxlib
  version: {{ version }}

source:
  fn: {{ fn }}
  url: https://pypi.io/packages/{{ pyver }}/{{ name[0] }}/{{ name }}/{{ fn }}
  sha256: 74490dd3c2e37492dbefc040a059bdedf0ba62d5d68c51d43181ac6c1aa14518  # [linux and py==36]
  sha256: 1b9fd8a29755c213e950a8eae128a1fed15e1055bea872e3b00e07ab9b00c05e  # [osx and py==36]

  sha256: 2dd207d8644186d7dcb8a35a85b1af0a822f1240425554ddaa8f93f9568f3962  # [linux and py==37]
  sha256: a82b68665c0f3ef94afb790cec9f300c08ceca8248d73474e940033a133e8d52  # [osx and py==37]

  sha256: 2beb7c0aed39ebdea4f07c04fdad491be544b627bb5194698466fa385684c070  # [linux and py==38]
  sha256: 31a3c55e28eaa9182e084e6233400d6e7d24f8eb9102f27e46bf52e8c8db2e02  # [osx and py==38]
build:
  number: 0
  skip: True  # [win or py2k]
  script: "{{ PYTHON }} -m pip install --no-deps -vv {{ fn }}"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - absl-py
    - numpy >=1.12
    - protobuf >=3.6.0
    - scipy
    - six

test:
  requires:
    - pip
  commands:
    - pip check
  # imports:
    # cannot run the test b/c this is not really manylinux1 GLIBC_2.14
    # Google :-/
    # - jaxlib

about:
  home: http://github.com/google/jax
  license: Apache-2.0
  license_file: LICENSE
  summary: "Composable transformations of Python+NumPy programs: differentiate, vectorize, JIT to GPU/TPU, and more"

  dev_url: http://github.com/google/jax

extra:
  recipe-maintainers:
    - ericmjl
