{% set version = "0.1.28" %}
{% set name = "jaxlib" %}

{% set wheel_tag = "cp37-none-manylinux2010_x86_64" %}  # [linux]
{% set wheel_tag = "cp37-none-macosx_10_9_x86_64" %}  # [osx]

{% set fn = "{}-{}-{}.whl".format(name, version, wheel_tag) %}

package:
  name: jaxlib
  version: {{ version }}

source:
  fn: {{ fn }}
  url: https://pypi.io/packages/cp37/{{ name[0] }}/{{ name }}/{{ fn }}
  sha256: 15043975fa6477ed61d4dae252a7f4d3a3a1f1c01b61efd3e8d932d6fab62b38  # [linux]
  sha256: d618d9e393b44972521ba39b97caffa9827a0b8c55ddf224a8d83a07289fff9a  # [osx]

build:
  number: 0
  skip: True  # [win or not py==37]
  script: "{{ PYTHON }} -m pip install --no-deps -vv {{ fn }}"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - absl-py
    - numpy >=1.12
    - protobuf >=3.6.0
    - scipy
    - six

test:
  imports:
    # cannot run the test b/c this is not really manylinux1 GLIBC_2.14
    # Google :-/
    # - jaxlib
    - numpy

about:
  home: http://github.com/google/jax
  license: Apache-2.0
  license_file: LICENSE
  summary: "Composable transformations of Python+NumPy programs: differentiate, vectorize, JIT to GPU/TPU, and more"

  dev_url: http://github.com/google/jax

extra:
  recipe-maintainers:
    - ericmjl
