travis:
  secure:
    BINSTAR_TOKEN: QyGVb4DzddcwLbbiUPd3d0HCzJ+jNhUmYWkodnCGVeAW23wSFIhRhMzVlQTkOsDcQ5HlwPePBoZa2u5uZpnVcFEyHMl+tBcDXIEZUh/2WfKzsw8ymJOWIMbiitgX1TBgeZSRkRgf9BwB3qRGXjkXd6jx4wA8cgrQzMZ8h52mSh30Vkz7p/GXXi1rah0XFewH0t4hxhzYPOtAxGyKLAPeEqKVv/TZ2eLWK1tqLiJzhjwVc/J/ZCYwWaqzz17+8ZADVUL93gaJi/CPK/GY9uSwFfBJue+5cUprssyXO2tAYRrE5lwnFGT2sH6mO8n1nz7jC/nYLM2s1A6bW6QDQZCFMa2RvG6c8JLt1Z6IN9QesBpiRoGNX1ZoqXP2SbGedM94RQKZgcMBwf87qhd8kmfwzTz8e1mjqk/x8gt0Xpw7dyHRIIQqi2rlWoD7JPaBsf1EHoL2Z1xcC81eWMKwM38EeHuqoH2+IS5grNUqG70ZvSrnqxKPpzYRFeXe39zA7suZNo0OduGlmsdMKL2xGzC7/WZ6BoQ+5gDOwByzyF9KALsCLwrFG7wVXhuZgHVGP4YPCodLxSqQG2bpNvFDTnRt6YVRgMo0sutFjlM+BG0VqdIfmQTyUQj0gjQqLIbMOc5ve2MpFpRsCj4kr7In7Ir/UfBkjUHHPfSArabqOu5GqYA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
